timeout: 1800s

steps:
- name: 'docker.io/moby/buildkit:v0.9.0'
  id: 'buildkit'
  entrypoint: 'buildctl-daemonless.sh'
  args:
    - 'build'
    - '--frontend=dockerfile.v0'
    - '--opt=source=docker/dockerfile:1.3'
    - '--opt=source=context:./'
    - '--progress=plain'
    - '--local=context=.'
    - '--local=dockerfile=.'
    - '--output=type=image,name=us-central1-docker.pkg.dev/$PROJECT_ID/minecraft-server/docker-minecraft-server,push=true'
  env:
    - 'BUILDKITD_FLAGS=--oci-worker-platform=linux/amd64'

- name: 'us-central1-docker.pkg.dev'
  id: 'sleep'
  entrypoint: 'sh'
  args:
    - '-c'
    - 'sleep 10'

images: ['us-central1-docker.pkg.dev/$PROJECT_ID/minecraft-server/docker-minecraft-server']