timeout: 1800s

options:
  machineType: 'E2_HIGHCPU_4'

steps:
- name: 'docker.io/moby/buildkit:v0.9.0'
  id: 'buildkit'
  entrypoint: 'buildctl-daemonless.sh'
  args:
    - 'build'
    - '--frontend=dockerfile.v0'
    - '--opt=source=docker/dockerfile:1.3'
    - '--opt=source=context:./'
    - '--progress=plain'
    - '--local=context=.'
    - '--local=dockerfile=.'
    - '--output=type=image,name=gcr.io/$PROJECT_ID/minecraft-server,push=true'
  env:
    - 'BUILDKITD_FLAGS=--oci-worker-platform=linux/amd64'

images: ['gcr.io/$PROJECT_ID/minecraft-server']